CREATE DATABASE [SAR]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SAR', FILENAME = N'D:\MSSQL\DATA\SAR.mdf' , SIZE = 4096KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SAR_log', FILENAME = N'D:\MSSQL\LOG\SAR_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [SAR] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [SAR] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SAR] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SAR] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SAR] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SAR] SET ARITHABORT OFF 
GO
ALTER DATABASE [SAR] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SAR] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SAR] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [SAR] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SAR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SAR] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SAR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SAR] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SAR] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SAR] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SAR] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SAR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SAR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SAR] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SAR] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SAR] SET  READ_WRITE 
GO
ALTER DATABASE [SAR] SET RECOVERY FULL 
GO
ALTER DATABASE [SAR] SET  MULTI_USER 
GO
ALTER DATABASE [SAR] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SAR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [SAR] SET DELAYED_DURABILITY = DISABLED 
GO
USE [SAR]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [SAR] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO




USE [SAR]
GO

/****** Object:  Table [dbo].[EQUIPOS]    Script Date: 31/05/2016 1:51:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EQUIPOS](
	[NU_SERIE] [varchar](7) NOT NULL,
	[MODELO] [varchar](30) NULL,
	[CARACTERIS] [varchar](255) NULL,
	[ESTADO] [varchar](4) NULL,
	[fecha_compra] [varchar](10) NULL,
 CONSTRAINT [PK_SAR_EQUIPOS] PRIMARY KEY CLUSTERED 
(
	[NU_SERIE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [SAR]
GO

/****** Object:  Table [dbo].[RENIEC]    Script Date: 31/05/2016 1:51:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RENIEC](
	[dni] [char](8) NULL,
	[nombre] [varchar](max) NULL,
	[fecha_nacimiento] [varchar](10) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

USE [SAR]
GO

/****** Object:  Table [dbo].[T_COLABORADOR]    Script Date: 31/05/2016 1:51:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[T_COLABORADOR](
	[COD_COLABORADOR] [int] NOT NULL,
	[NOM_COLABORADOR] [varchar](50) NULL,
	[FEC_NACIMIENTO] [smalldatetime] NULL,
	[FEC_INGRESO] [smalldatetime] NULL,
	[CAR_COLABORADOR] [varchar](50) NULL,
	[ESTADO] [varchar](50) NULL DEFAULT ('Activo'),
PRIMARY KEY CLUSTERED 
(
	[COD_COLABORADOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

