//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject1.EquiposWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Equipo", Namespace="http://schemas.datacontract.org/2004/07/SARSOAPService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Equipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaracterisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_compraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nu_serieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caracteris {
            get {
                return this.CaracterisField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracterisField, value) != true)) {
                    this.CaracterisField = value;
                    this.RaisePropertyChanged("Caracteris");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_compra {
            get {
                return this.Fecha_compraField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_compraField, value) != true)) {
                    this.Fecha_compraField = value;
                    this.RaisePropertyChanged("Fecha_compra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nu_serie {
            get {
                return this.Nu_serieField;
            }
            set {
                if ((object.ReferenceEquals(this.Nu_serieField, value) != true)) {
                    this.Nu_serieField = value;
                    this.RaisePropertyChanged("Nu_serie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/SARSOAPService.Errores")]
    [System.SerializableAttribute()]
    public partial class RepetidoException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EquiposWS.IEquipos")]
    public interface IEquipos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/CrearEquipo", ReplyAction="http://tempuri.org/IEquipos/CrearEquipoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UnitTestProject1.EquiposWS.RepetidoException), Action="http://tempuri.org/IEquipos/CrearEquipoRepetidoExceptionFault", Name="RepetidoException", Namespace="http://schemas.datacontract.org/2004/07/SARSOAPService.Errores")]
        UnitTestProject1.EquiposWS.Equipo CrearEquipo(UnitTestProject1.EquiposWS.Equipo equipoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/CrearEquipo", ReplyAction="http://tempuri.org/IEquipos/CrearEquipoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.EquiposWS.Equipo> CrearEquipoAsync(UnitTestProject1.EquiposWS.Equipo equipoACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerEquipo", ReplyAction="http://tempuri.org/IEquipos/ObtenerEquipoResponse")]
        UnitTestProject1.EquiposWS.Equipo ObtenerEquipo(string nu_serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerEquipo", ReplyAction="http://tempuri.org/IEquipos/ObtenerEquipoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.EquiposWS.Equipo> ObtenerEquipoAsync(string nu_serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ModificarEquipo", ReplyAction="http://tempuri.org/IEquipos/ModificarEquipoResponse")]
        UnitTestProject1.EquiposWS.Equipo ModificarEquipo(UnitTestProject1.EquiposWS.Equipo equipoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ModificarEquipo", ReplyAction="http://tempuri.org/IEquipos/ModificarEquipoResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.EquiposWS.Equipo> ModificarEquipoAsync(UnitTestProject1.EquiposWS.Equipo equipoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/EliminarEquipos", ReplyAction="http://tempuri.org/IEquipos/EliminarEquiposResponse")]
        void EliminarEquipos(string nu_serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/EliminarEquipos", ReplyAction="http://tempuri.org/IEquipos/EliminarEquiposResponse")]
        System.Threading.Tasks.Task EliminarEquiposAsync(string nu_serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEquipos", ReplyAction="http://tempuri.org/IEquipos/ListarEquiposResponse")]
        UnitTestProject1.EquiposWS.Equipo[] ListarEquipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEquipos", ReplyAction="http://tempuri.org/IEquipos/ListarEquiposResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.EquiposWS.Equipo[]> ListarEquiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEnStock", ReplyAction="http://tempuri.org/IEquipos/ListarEnStockResponse")]
        UnitTestProject1.EquiposWS.Equipo[] ListarEnStock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEnStock", ReplyAction="http://tempuri.org/IEquipos/ListarEnStockResponse")]
        System.Threading.Tasks.Task<UnitTestProject1.EquiposWS.Equipo[]> ListarEnStockAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEquiposChannel : UnitTestProject1.EquiposWS.IEquipos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquiposClient : System.ServiceModel.ClientBase<UnitTestProject1.EquiposWS.IEquipos>, UnitTestProject1.EquiposWS.IEquipos {
        
        public EquiposClient() {
        }
        
        public EquiposClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquiposClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquiposClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquiposClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnitTestProject1.EquiposWS.Equipo CrearEquipo(UnitTestProject1.EquiposWS.Equipo equipoACrear) {
            return base.Channel.CrearEquipo(equipoACrear);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.EquiposWS.Equipo> CrearEquipoAsync(UnitTestProject1.EquiposWS.Equipo equipoACrear) {
            return base.Channel.CrearEquipoAsync(equipoACrear);
        }
        
        public UnitTestProject1.EquiposWS.Equipo ObtenerEquipo(string nu_serie) {
            return base.Channel.ObtenerEquipo(nu_serie);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.EquiposWS.Equipo> ObtenerEquipoAsync(string nu_serie) {
            return base.Channel.ObtenerEquipoAsync(nu_serie);
        }
        
        public UnitTestProject1.EquiposWS.Equipo ModificarEquipo(UnitTestProject1.EquiposWS.Equipo equipoAModificar) {
            return base.Channel.ModificarEquipo(equipoAModificar);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.EquiposWS.Equipo> ModificarEquipoAsync(UnitTestProject1.EquiposWS.Equipo equipoAModificar) {
            return base.Channel.ModificarEquipoAsync(equipoAModificar);
        }
        
        public void EliminarEquipos(string nu_serie) {
            base.Channel.EliminarEquipos(nu_serie);
        }
        
        public System.Threading.Tasks.Task EliminarEquiposAsync(string nu_serie) {
            return base.Channel.EliminarEquiposAsync(nu_serie);
        }
        
        public UnitTestProject1.EquiposWS.Equipo[] ListarEquipos() {
            return base.Channel.ListarEquipos();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.EquiposWS.Equipo[]> ListarEquiposAsync() {
            return base.Channel.ListarEquiposAsync();
        }
        
        public UnitTestProject1.EquiposWS.Equipo[] ListarEnStock() {
            return base.Channel.ListarEnStock();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject1.EquiposWS.Equipo[]> ListarEnStockAsync() {
            return base.Channel.ListarEnStockAsync();
        }
    }
}
